# examples/feature_first_example/analysis_options.yaml

analyzer:
  plugins:
    # This enables the custom_lint engine
    - custom_lint

custom_lint:
  # This tells custom_lint to look for rules in your local package
  # (Assuming architecture_lints is in your dev_dependencies)
  debug: true

  # If you wanted to DISABLE a specific rule, you would do this:
  rules:
    - arch_orphan_file: true
    - arch_antipattern_naming: true
    - arch_pattern_naming: true

