# feature_first_example/analysis_options.yaml

formatter:
  page_width: 100

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

custom_lint:
  rules:
    # --- ENABLE ALL LINT RULES ---
    # 1. Purity & Responsibility Rules
    - disallow_model_in_domain: true
    - disallow_entity_in_data_source: true
    - disallow_repository_in_presentation: true
    - disallow_model_return_from_repository: true
    - disallow_use_case_in_widget: true
    - disallow_flutter_in_domain: true
    - disallow_public_members_in_implementation: true
    - disallow_dependency_instantiation: true
    - disallow_service_locator: true

    # 2. Contract & Inheritance Rules
    - enforce_model_to_entity_mapping: true
    - enforce_model_inherits_entity: true
    - enforce_port_contract: true # Replaces enforce_repository_contract
    - enforce_usecase_contract: true # Replaces enforce_use_case_contract (naming fix)
    - enforce_entity_contract: true
    - enforce_repository_contract: true # Replaces enforce_repository_implementation_contract
    - enforce_custom_inheritance: true

    # 3. Dependency & Structure Rules
    - enforce_layer_independence: true
    - enforce_abstract_data_source_dependency: true
    - enforce_abstract_repository_dependency: true
    - enforce_file_and_folder_location: true

    # 4. Type Safety & Error Handling Rules
    - enforce_type_safety: true
    - disallow_throwing_from_repository: true
    - enforce_try_catch_in_repository: true
    - enforce_exception_on_data_source: true
    - convert_exceptions_to_failures: true # Enable the new rule
    - disallow_throwing_from_presentation: true # Enable the new rule

    # 5. Naming Convention Rules
    - enforce_naming_antipattern: true
    - enforce_naming_pattern: true
    - enforce_semantic_naming: true

    # 6. Code Generation Rule
    - missing_use_case: true

    # --- CONFIGURATION BLOCK ---
    - clean_architecture:
      # [1. Structure] Define the high-level project structure.
      module_definitions:
        type: 'feature_first' # or 'layer_first'
        core: 'core'
        features: 'features'
        # layers can be used for both feature_first and layer_first naming.
        # all layer components accept a single string or a list of strings.
        layers:
          domain: 'domain'
          data: 'data'
          presentation: 'presentation'

      # [2. Components] Define directory names for architectural components.
      layer_definitions:
        domain:
          entity: 'entities'
          ports: 'ports'
          usecase: 'usecases'

        data:
          model: 'models'
          source: 'sources'
          repository: 'repositories'

        presentation:
          manager: ['managers', 'bloc', 'cubit']
          widget: 'widgets'
          page: 'pages'

      # [3. Inheritance] Define base classes for components.
      inheritances:
        # --- Domain Layer ---
        # The default rule used for [enforce_entity_contract].
        # Defining not required unless for overringing the values.
        - on: entity
          required:
            name: 'Entity'
            import: 'package:example/core/entity/entity.dart'

        # The default rule used for [enforce_port_contract].
        # Defining not required unless for overringing the values.
        - on: port
          required:
            name: 'Port'
            import: 'package:example/core/port/port.dart'

        # The default rule used for [enforce_usecase_contract].
        # Defining not required unless for overringing the values.
        - on: usecase
          required:
            name: ['NullaryUsecase', 'UnaryUsecase']
            import: 'package:example/core/usecase/usecase.dart'

        # --- Data Layer ---
        # The default rule used for [enforce_abstracting_model].
        # Defining is not required unless for overringing the values.
        - on: model
          required:
            component: 'entity'

        # The default rule used for [enforce_source_contract].
        # Defining is not required unless for overringing the values.
        - on: source.interface
          required:
            name: 'Source'
            import: 'package:example/core/source/source.dart'

        # The default rule used for [enforce_abstracting_source_implementation].
        # Defining not required unless for overringing the values.
        - on: source.implementation
          required:
            component: 'source.interface'

        # The default rule used for [enforce_abstracting_repository].
        # Defining is not required unless for overringing the values.
        - on: repository
          required:
            component: 'port'

        # --- Presentation Layer ---
        # User default rule for [enforce_custom_inheritance].
        # Defining is required in order the lint to work.
        - on: manager
          allowed:
            name: ['Bloc', 'Cubit']
            import: 'package:bloc/bloc.dart'

        # User default rule for [enforce_custom_inheritance].
        # Defining is required in order the lint to work.
        - on: widget
          allowed:
            name: 'HookWidget'
            import: 'package:flutter_hooks/flutter_hooks.dart'

        # User default rule for [enforce_custom_inheritance].
        # Defining is required in order the lint to work.
        - on: page
          forbidden:
            name: 'StatefulWidget'
            import: 'package:flutter/widgets.dart'

      naming_conventions:
        # --- Domain Layer ---
        # The default rule used for [domain_naming_conventions] and [domain_semantic_naming].
        # Defining is not required unless for overringing the values.
        - on: entity
          pattern: '{{name}}'
          antipattern: '{{name}}Entity'
          grammar: '{{noun.phrase}}'

        # The default rule used for [enforce_naming_conventions] and [enforce_semantic_naming].
        # Defining is not required unless for overringing the values.
        - on: port
          pattern: '{{name}}Port'
          grammar: '{{noun.phrase}}Port'

        # The default rule used for [enforce_naming_conventions] and [enforce_semantic_naming].
        # Defining is not required unless for overringing the values.
        - on: usecase
          pattern: '{{name}}'
          antipattern: '{{name}}Use(C|c)ase'
          grammar: '{{verb.present}}{{noun.phrase}}'

        # The default rule used for [enforce_naming_conventions] and [create_usecase_fix].
        # Defining is not required unless for overringing the values.
        - on: usecase.parameter
          pattern: '_{{name}}Param'

        # --- Data Layer ---
        # The default rule used for [data_naming_conventions] and [data_semantic_naming].
        # Defining is not required unless for overringing the values
        - on: model
          pattern: '{{name}}Model'
          grammar: '{{noun.phrase}}Model'

        # The default two rules used for [data_naming_conventions] and [data_semantic_naming].
        # Defining is not required unless for overringing the values
        - on: source.interface
          pattern: '{{name}}Source'
          grammar: '{{noun.phrase}}Source'
        - on: source.implementation
          pattern: 'Default{{name}}Source'
          grammar: 'Default{{noun.phrase}}Source'

        # The default rule used for [data_naming_conventions] and [data_semantic_naming].
        # Defining is not required unless for overringing the values
        - on: repository
          pattern: '{{kind}}{{name}}Repository'

        # --- Presentation Layer ---
        # The default five rules used for [manager_naming_conventions] and
        # [manager_semantic_naming].
        # Defining is not required unless for overringing the values
        - on: manager
          pattern: '{{name}}(Bloc|Cubit|Manager)'
          grammar: '{{noun.phrase}}(Bloc|Cubit|Manager)'
        - on: event.interface
          pattern: '{{name}}Event'
          grammar: '{{noun.phrase}}Event'
        - on: event.implementation
          pattern: '{{name}}'
          grammar: '{{subject}}{{noun.phrase}}?{{verb.past}}'
        - on: state.interface
          pattern: '{{name}}State'
          grammar: '{{noun.singular}}State'
        - on: state.implementation
          pattern: '{{name}}'
          grammar: '{{subject}}({{adjective}}|{{verb.gerund}}|{{verb.past}})'

        # The default rule used for [widget_naming_conventions] and [widget_semantic_naming].
        # Defining is not required unless for overringing the values
        - on: widget
          pattern: '{{name}}(Form|Panel|Section|Widget)'
          grammar: '{{noun.phrase}}(Form|Panel|Section|Widget)'

        # The default rule used for [page_naming_conventions] and [page_semantic_naming].
        # Defining is not required unless for overringing the values
        - on: page
          pattern: '{{name}}Page'
          grammar: '{{noun.phrase}}Page'

      dependencies:
        # --- Domain Layer ---
        # The default rule used for [no_flutter_in_domain_layer].
        # Defining is not required unless for overringing the values.
        - on: domain
          forbidden:
            package: ['package:flutter/**', 'dart:ui']

        # The default rule used for [entity_in_domain_layer].
        # Defining is not required unless for overringing the values.
        - on: entity
          allowed: ['domain', 'manager']

        # The default rule used for [port_in_repository].
        # Defining is not required unless for overringing the values.
        - on: port
          allowed: 'repository'

        # The default rule used for [usecase_in_repository].
        # Defining is not required unless for overringing the values.
        - on: usecase
          allowed: 'repository'

        # --- Data Layer ---
        # The default rule used for [model_in_data_layer].
        # Defining is not required unless for overringing the values.
        - on: model
          allowed: 'data'

        # The default two rules used for [source_in_repository].
        # Defining is not required unless for overringing the values.
        - on: source.interface
          allowed: 'source.implementation'
        - on: source.implementation
          allowed: 'repository'

        # The default rule used for [repository_in_data_layer].
        # Defining is not required unless for overringing the values.
        - on: repository
          allowed: 'data'

        # --- Presentation Layer ---
        # The default rule used for [manager_in_user_interface].
        # Defining is not required unless for overringing the values.
        - on: ['manager', 'event', 'state']
          allowed: ['widget', 'page']

        # The default rule used for [widget_in_user_interface].
        # Defining is not required unless for overringing the values.
        - on: 'widget'
          allowed: ['widget', 'page']

        # The default rule used for [page_in_user_interface].
        # Defining is not required unless for overringing the values.
        - on: 'page'
          allowed: ['page', 'core']

      # Default types used in [type_safeties] and [error_handlers] configurations.
      # Defining is not required unless for overringing values.
      type_definitions:
        # --- Domain Failures ---
        failure:
          base:
            name: 'Failure'
            import: 'package:example/core/error/failures.dart'
          server:
            name: 'ServerFailure'
            import: 'package:example/core/error/failures.dart'
          cache:
            name: 'CacheFailure'
            import: 'package:example/core/error/failures.dart'

        # --- Data Exceptions ---
        exception:
          raw:
            name: 'Exception'
          base:
            name: 'CustomException'
            import: 'package:example/core/error/exceptions.dart'
          server:
            name: 'ServerException'
            import: 'package:example/core/error/exceptions.dart'
          cache:
            name: 'CacheException'
            import: 'package:example/core/error/exceptions.dart'

        # --- Functional Results (Wrappers) ---
        result:
          future:
            name: 'Future'
          # Define the "Safe Return" wrapper (Functional Programming).
          wrapper:
            name: 'FutureEither'
            import: 'package:example/core/utils/types.dart'

          success:
            name: 'Right'
            import: 'package:fpdart/fpdart.dart'

          failure:
            name: 'Left'
            import: 'package:fpdart/fpdart.dart'

        # --- Value Objects (Identity) ---
        identity:
          integer:
            name: 'IntId'
            import: 'package:example/core/utils/types.dart'

          string:
            name: 'StringId'
            import: 'package:example/core/utils/types.dart'

      type_safeties:
        # The default rule used for [domain_layer_type_safety].
        # Defining is not required unless for overringing the values.
        # Port and Usecase must return wrapper FutureEither.
        - on: [ port, usecase ]
          returns:
            unsafe_type: 'result.future'
            safe_type: 'result.wrapper'

        # The default rule used for [data_layer_type_safety].
        # Defining is not required unless for overringing the values.
        # Source Interface and Implementation must return raw Futures.
        - on: source
          returns:
            unsafe_type: 'result.wrapper'
            safe_type: 'result.future'

        # User defined rule used for [enforce_custom_type_safety].
        # Defining is required in order the lint to work.
        # Strong ID parameter enforcement.
        - on: [ port, usecase, source, repository ]
          parameters:
            - unsafe_type: 'int'
              identifier: 'id'
              safe_type: 'identity.integer'

            - unsafe_type: 'String'
              identifier: 'id'
              safe_type: 'identity.string'

      # [3] ERROR HANDLING: Control Flow & Logic Enforcement
      error_handlers:
        # --- 1. The Producer (Data Source) ---
        # Default rule used for [exception_on_source_implementation].
        # Defining is not required unless for overringing the default values.
        # Responsible for interacting with external worlds and throwing specific exceptions.
        - on: source.implementation
          role: 'producer'
          required:
            # Must have a try block which returns any Object
            - operation: 'try_return'
              target_type: 'Object'
            # Must have a catch block which throws a subtype of CustomException
            - operation: 'catch_throw'
              target_type: 'exception.base'
          forbidden:
            # Never throw a raw Dart Exception directly.
            operation: 'throw'
            target_type: 'exception.raw'

        # --- 2. The Boundary (Repository) ---
        # Default rule used for [no_throwing_from_repository], [try_catch_in_repository], and
        # [convert_exceptions_to_failures].
        # Defining is not required unless for overringing the default values.
        # Responsible for catching Exceptions and converting them to Failures.
        - on: repository
          role: 'boundary'
          required:
            # Must have a try block which returns a subtype of Either
            - operation: 'try_return'
              target_type: 'result.success'
            # Must have a catch block which returns a subtype of Failure
            - operation: 'catch_return'
              target_type: 'result.failure'
          forbidden:
            # Never let an exception escape the repository.
            operation: ['throw', 'rethrow']

          # Enforce 1-to-1 mapping between Data Errors and Domain Failures
          conversions:
            # Convert ServerException to ServerFailure.
            - from_type: 'exception.server'
              to_type: 'failure.server'
            # Convert CacheException to CacheFailure
            - from_type: 'exception.cache'
              to_type: 'failure.cache'
            # A fallback to convert Exception or CustomException to Generic Failure.
            - from_type: 'exception.base'
              to_type: 'failure.base'

        # --- 3. The Consumer (Presentation) ---
        # Default rule used for [no_throwing_from_presentation].
        # Defining is not required unless for overringing the default values.
        # Responsible for mapping Failures to user messages/states.
        - on: presentation
          role: 'consumer'
          forbidden:
            # Must not throw or rethrow any subtype of dart Exception.
            operation: ['throw', 'rethrow']
            target_type: 'exception.raw'

      annotations:
        # --- Domain Layer ---
        # User defined rule used for [enforce_annotation].
        # Defining is required in order the lint to work.
        - on: entity
          forbidden:
            name: [ 'injectable', 'LazySingleton' ]
            import: 'package:injectable/injectable.dart'

        # User defined rule used for [enforce_annotation].
        # Defining is required in order the lint to work.
        - on: usecase
          required:
            name: 'Injectable'
            import: 'package:injectable/injectable.dart'

        # --- Data Layer ---
        # User defined rule used for [enforce_annotation].
        # Defining is required in order the lint to work.
        - on: model
          allowed:
            - name: 'freezed'
              import: 'package:freezed_annotation/freezed_annotation.dart'
            - name: 'MappableClass'
              import: 'package:dart_mappable/dart_mappable.dart'

        # User defined rule used for [enforce_annotation].
        # Defining is required in order the lint to work.
        - on: repository
          required:
            name: ['LazySingleton', 'Singleton']
            import: 'package:injectable/injectable.dart'
          allowed:
            name: 'WithCache'
            import: 'package:cached_annotation/cached_annotation.dart'

      # Configuration for service-related lints.
      services:
        # The default rule used for [disallow_service_locator].
        # Defining is not required unless for overringing the values.
        service_locator:
          name: ['getIt', 'locator']
          import: 'package:example/core/utils/service_locator.dart'
